# Generated by Django 3.2 on 2021-04-16 15:42

from django.db import migrations, models
import imagekit.models.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_auto_20210416_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='articles/%Y/%m/%d/', verbose_name='配图')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('supports', models.PositiveIntegerField(default=0, verbose_name='点赞量')),
                ('isPrivate', models.BooleanField(default=False, verbose_name='是否私密')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'tb_articles',
                'ordering': ['-updated'],
            },
        ),
    ]
